version: '3.0'
services:
  app:
    build: ./app
    ports: 
      - "80:80"
    restart: always
    links:
      - mysql
  mysql:
    build:
      context: ./mysql
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    

